# Generated by Django 4.2.16 on 2025-12-16 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0002_umrahcity_umrahroom_rename_city_holidaycity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holidayenquiry',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='holidayenquiry',
            name='room_details',
        ),
        migrations.AddField(
            model_name='holidaycity',
            name='enquiry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='Holidays.holidayenquiry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='holidayroom',
            name='enquiry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='room_details', to='Holidays.holidayenquiry'),
            preserve_default=False,
        ),
    ]
