# Generated by Django 4.2.16 on 2025-12-16 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0003_remove_holidayenquiry_cities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='email',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='message',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='subject',
        ),
    ]
