# Generated by Django 4.2.16 on 2025-12-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0004_remove_enquiry_email_remove_enquiry_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holidayroom',
            name='enquiry',
        ),
        migrations.AddField(
            model_name='holidayenquiry',
            name='cities',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='holidayenquiry',
            name='room_details',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='HolidayCity',
        ),
        migrations.DeleteModel(
            name='HolidayRoom',
        ),
    ]
