# Generated by Django 4.2.16 on 2025-12-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0005_remove_holidayroom_enquiry_holidayenquiry_cities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='umrahenquiry',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='umrahenquiry',
            name='room_details',
        ),
        migrations.DeleteModel(
            name='UmrahCity',
        ),
        migrations.DeleteModel(
            name='UmrahRoom',
        ),
        migrations.AddField(
            model_name='umrahenquiry',
            name='cities',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='umrahenquiry',
            name='room_details',
            field=models.JSONField(default=list),
        ),
    ]
