# Generated by Django 4.2.16 on 2025-12-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0006_remove_umrahenquiry_cities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidayenquiry',
            name='package_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='umrahenquiry',
            name='package_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
