# Generated by Django 4.2.16 on 2025-12-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0008_holidaypackage_itineraryday_inclusion_exclusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidaypackage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
