# Generated by Django 4.2.16 on 2025-12-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0013_startingcity'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidaypackage',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
