# Generated by Django 4.2.16 on 2025-12-23 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0017_destination_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Holidays.destination')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_destinations', to='Holidays.holidaypackage')),
            ],
        ),
    ]
