# Generated by Django 4.2.16 on 2025-12-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0018_packagedestination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holidaypackage',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='holidaypackage',
            name='nights',
        ),
        migrations.AddField(
            model_name='packagedestination',
            name='nights',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
