# Generated by Django 4.2.16 on 2025-12-23 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0020_itinerarymaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryday',
            name='master_template',
            field=models.ForeignKey(blank=True, help_text='Optional: Select a master template to pre-populate or reference data.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Holidays.itinerarymaster'),
        ),
    ]
