# Generated by Django 4.2.16 on 2026-01-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0023_umrahdestination'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidayenquiry',
            name='adults',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='holidayenquiry',
            name='children',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='holidayenquiry',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='umrahenquiry',
            name='adults',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='umrahenquiry',
            name='children',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='umrahenquiry',
            name='infants',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='umrahenquiry',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
