# Generated by Django 4.2.16 on 2026-01-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0025_highlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidaypackage',
            name='with_flight',
            field=models.BooleanField(default=False),
        ),
    ]
