# Generated by Django 4.2.16 on 2026-01-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0027_visa_visaenquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='visa',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='visas/'),
        ),
    ]
