# Generated by Django 4.2.16 on 2026-01-12 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0028_visa_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisaEnquiry',
        ),
    ]
