# Generated by Django 4.2.16 on 2026-01-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0029_delete_visaenquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='visa',
            name='entry_type',
            field=models.CharField(default='Single Entry', max_length=50),
        ),
        migrations.AddField(
            model_name='visa',
            name='government_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visa',
            name='method',
            field=models.CharField(default='Paperless', max_length=50),
        ),
        migrations.AddField(
            model_name='visa',
            name='requirements',
            field=models.TextField(blank=True, help_text='List items separated by new lines'),
        ),
        migrations.AddField(
            model_name='visa',
            name='service_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visa',
            name='stay_period',
            field=models.CharField(default='30 days', max_length=50),
        ),
        migrations.AddField(
            model_name='visa',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='visa',
            name='validity_period',
            field=models.CharField(default='60 days', max_length=50),
        ),
        migrations.AddField(
            model_name='visa',
            name='visa_type',
            field=models.CharField(default='E-Visa', max_length=50),
        ),
    ]
