# Generated by Django 4.2.16 on 2026-01-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0030_visa_entry_type_visa_government_fee_visa_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visa',
            name='image',
        ),
        migrations.AddField(
            model_name='visa',
            name='card_image',
            field=models.ImageField(blank=True, null=True, upload_to='visas/cards/'),
        ),
        migrations.AddField(
            model_name='visa',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='visas/headers/'),
        ),
    ]
