# Generated by Django 4.2.16 on 2026-01-19 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0033_alter_visa_method_alter_visa_visa_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visa',
            name='method',
        ),
    ]
