# Generated by Django 6.0 on 2026-01-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0039_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
    ]
