# Generated by Django 4.2.16 on 2026-01-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0041_visa_visa_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidaypackage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
