# Generated by Django 4.2.16 on 2026-01-23 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0045_visaapplicant_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='visa',
            name='photography_required',
            field=models.TextField(blank=True, help_text='Comma-separated list of photography requirements'),
        ),
        migrations.AlterField(
            model_name='visa',
            name='visa_type',
            field=models.CharField(choices=[('Sticker Visa', 'Sticker Visa'), ('E-Visa', 'E-Visa')], default='E-Visa', max_length=50),
        ),
    ]
