# Generated by Django 4.2.16 on 2026-01-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0047_alter_visa_visa_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visa',
            name='entry_type',
            field=models.CharField(choices=[('Single-Entry Visa', 'Single-Entry Visa'), ('Double-Entry Visa', 'Double-Entry Visa'), ('Multiple-Entry Visa', 'Multiple-Entry Visa'), ('Transit Visa', 'Transit Visa'), ('Visa on Arrival', 'Visa on Arrival'), ('Electronic Visa (e-Visa)', 'Electronic Visa (e-Visa)'), ('Re-Entry Visa', 'Re-Entry Visa')], default='Single-Entry Visa', max_length=50),
        ),
    ]
