# Generated by Django 4.2.16 on 2026-01-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0049_visa_card_image_visa_header_image_visa_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visa',
            name='header_image',
        ),
        migrations.RemoveField(
            model_name='visa',
            name='video',
        ),
        migrations.AddField(
            model_name='country',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='countries/headers/'),
        ),
        migrations.AddField(
            model_name='country',
            name='video',
            field=models.FileField(blank=True, help_text='Upload a video for the country header', null=True, upload_to='countries/videos/'),
        ),
    ]
