# Generated by Django 4.2.16 on 2026-01-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0050_remove_visa_header_image_remove_visa_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visa',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='visas/headers/'),
        ),
        migrations.AddField(
            model_name='visa',
            name='video',
            field=models.FileField(blank=True, help_text='Indiviual video for this specific visa', null=True, upload_to='visas/videos/'),
        ),
    ]
