# Generated by Django 4.2.16 on 2026-01-23 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0051_visa_header_image_visa_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visa',
            name='card_image',
        ),
        migrations.RemoveField(
            model_name='visa',
            name='header_image',
        ),
        migrations.RemoveField(
            model_name='visa',
            name='video',
        ),
        migrations.CreateModel(
            name='VisaAdditionalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(upload_to='visa_apps/additional_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_documents', to='Holidays.visaapplicant')),
            ],
        ),
    ]
