# Generated by Django 4.2.16 on 2026-01-24 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0054_enquiry_destination_enquiry_enquiry_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='header_image',
        ),
        migrations.RemoveField(
            model_name='country',
            name='video',
        ),
    ]
