# Generated by Django 4.2.16 on 2026-01-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0056_remove_visa_header_image_remove_visa_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidaypackage',
            name='card_image',
            field=models.ImageField(blank=True, null=True, upload_to='packages/cards/'),
        ),
        migrations.AlterField(
            model_name='holidaypackage',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='packages/headers/'),
        ),
    ]
