# Generated by Django 4.2.16 on 2026-01-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0061_alter_visa_options_remove_visa_price_visa_cost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='card_image',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/cards/'),
        ),
        migrations.AddField(
            model_name='destination',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visa',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
