# Generated by Django 4.2.16 on 2026-02-24 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0064_cruisecalendar_pax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cruisecalendar',
            name='pax',
        ),
    ]
