# Generated by Django 4.2.16 on 2026-02-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0067_holidaypackage_arrival_airport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidaypackage',
            name='arrival_airline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='holidaypackage',
            name='arrival_flight_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='holidaypackage',
            name='departure_airline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='holidaypackage',
            name='departure_flight_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
