# Generated by Django 4.2.16 on 2026-02-26 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0069_airline'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(max_length=200)),
                ('no_of_vehicles', models.PositiveIntegerField(default=1)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('pickup_location', models.TextField(blank=True, null=True)),
                ('dropoff_date', models.DateField(blank=True, null=True)),
                ('dropoff_location', models.TextField(blank=True, null=True)),
                ('vehicle_brand', models.CharField(blank=True, max_length=200, null=True)),
                ('pickup_time', models.TimeField(blank=True, null=True)),
                ('dropoff_time', models.TimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='Holidays.holidaypackage')),
            ],
        ),
    ]
