# Generated by Django 4.2.16 on 2026-02-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0070_holidayvehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryday',
            name='details_json',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='itinerarymaster',
            name='details_json',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
