# Generated by Django 4.2.16 on 2026-02-26 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0073_importantpoints_cancellationpolicy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImportantPoints',
        ),
    ]
