# Generated by Django 4.2.16 on 2026-02-26 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0074_delete_importantpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidaypackage',
            name='ending_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='holidaypackage',
            name='fixed_departure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='holidaypackage',
            name='package_categories',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='holidaypackage',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='Holidays.supplier'),
        ),
    ]
