# Generated by Django 4.2.16 on 2026-02-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0076_sightseeingmaster_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidaypackage',
            name='sharing',
            field=models.CharField(blank=True, choices=[('TWIN', 'TWIN'), ('TRIPLE', 'TRIPLE'), ('QUAD', 'QUAD'), ('QUINT', 'QUINT')], default='TWIN', max_length=20, null=True),
        ),
    ]
