# Generated by Django 4.2.16 on 2026-03-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0083_vehiclemaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('id_no', models.CharField(max_length=255)),
                ('id_copy', models.FileField(blank=True, null=True, upload_to='driver_ids/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='drivers/')),
                ('mobile_number', models.CharField(max_length=20)),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
