# Generated by Django 4.2.16 on 2026-03-05 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0087_alter_vehiclemaster_brand_alter_vehiclemaster_drive_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupPointMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_points', to='Holidays.destination')),
            ],
        ),
    ]
