# Generated by Django 4.2.16 on 2026-03-06 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0088_pickuppointmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accommodation_templates', to='Holidays.destination'),
        ),
    ]
