# Generated by Django 4.2.16 on 2026-03-09 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0090_cabbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclemaster',
            name='drive',
        ),
    ]
