# Generated by Django 4.2.16 on 2026-03-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0092_vehicleratecard_column_vehicles'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabbooking',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
