# Generated by Django 4.2.16 on 2026-03-09 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0095_vehicleratecard_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleratecard',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate_cards', to='Holidays.vehiclemaster'),
        ),
    ]
