# Generated by Django 4.2.16 on 2026-03-10 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0096_vehicleratecard_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabbooking',
            name='confirmation_doc',
            field=models.FileField(blank=True, null=True, upload_to='cab_bookings/'),
        ),
        migrations.CreateModel(
            name='CabAdditionalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(upload_to='cab_bookings/additional/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_documents', to='Holidays.cabbooking')),
            ],
        ),
    ]
