# Generated by Django 4.2.16 on 2026-03-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0100_alter_cabbooking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabbooking',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='cab_bookings/invoices/'),
        ),
    ]
