# Generated by Django 4.2.16 on 2026-03-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0101_cabbooking_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabbooking',
            name='confirmation_doc',
        ),
        migrations.AlterField(
            model_name='cabbooking',
            name='invoice',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
