# Generated by Django 4.2.16 on 2026-03-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0102_remove_cabbooking_confirmation_doc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabbooking',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
