# Generated by Django 4.2.16 on 2026-03-12 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0103_cabbooking_invoice_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabbooking',
            name='invoice',
        ),
    ]
