# Generated by Django 4.2.16 on 2026-03-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0104_remove_cabbooking_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabbooking',
            name='status',
            field=models.CharField(choices=[('First Booking Requested', 'First Booking Requested'), ('Tentative payment', 'Tentative payment'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='First Booking Requested', max_length=50),
        ),
    ]
