# Generated by Django 4.2.16 on 2026-03-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0107_vehicleratecard_rate_card_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidaypackage',
            name='accommodations_raw',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='holidaypackage',
            name='arrival_no_of_nights',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
