# Generated by Django 4.2.16 on 2026-03-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0110_holidaypackage_terms_and_policies_raw'),
    ]

    operations = [
        migrations.CreateModel(
            name='CantonEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('business_name', models.CharField(max_length=255)),
                ('selected_phase', models.CharField(max_length=150)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
