# Generated by Django 4.2.16 on 2026-04-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0117_delete_country_delete_startingcity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabbooking',
            name='status',
            field=models.CharField(choices=[('Booking Requested', 'Booking Requested'), ('Tentative Confirmation', 'Tentative Confirmation'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Booking Requested', max_length=50),
        ),
    ]
