# Generated by Django 4.2.16 on 2026-04-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0125_airport_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='CruiseTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal_name', models.CharField(max_length=255)),
                ('cruise_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cruise_code', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
