# Generated by Django 4.2.16 on 2026-04-06 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0130_cabbooking_airport_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cruiseterminal',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cruise_terminals', to='Holidays.city'),
        ),
        migrations.AlterField(
            model_name='pickuppointmaster',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_points', to='Holidays.city'),
        ),
    ]
