# Generated by Django 4.2.16 on 2026-04-07 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0131_cruiseterminal_city_alter_pickuppointmaster_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodation',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='itinerarymaster',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='sightseeingmaster',
            name='destination',
        ),
        migrations.AddField(
            model_name='accommodation',
            name='city_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accommodation_templates', to='Holidays.city'),
        ),
        migrations.AddField(
            model_name='itinerarymaster',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itinerary_templates', to='Holidays.city'),
        ),
        migrations.AddField(
            model_name='sightseeingmaster',
            name='city_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sightseeing_templates', to='Holidays.city'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='enquiry_type',
            field=models.CharField(choices=[('General', 'General'), ('Cab', 'Cab'), ('Cruise', 'Cruise'), ('Hotel', 'Hotel'), ('Business Travel', 'Business Travel')], default='General', max_length=50),
        ),
        migrations.AlterField(
            model_name='packagedestination',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Holidays.city'),
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
