# Generated by Django 4.2.16 on 2026-07-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0134_cabbooking_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabbooking',
            name='status',
            field=models.CharField(choices=[('Booking Requested', 'Booking Requested'), ('Tentative Confirmation', 'Tentative Confirmation'), ('defined', 'defined'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Booking Requested', max_length=50),
        ),
    ]
