# Generated by Django 4.2.16 on 2026-07-18 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0137_cabbooking_zoho_access_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisaArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='visa_articles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visa_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Holidays.visaarticle')),
            ],
        ),
    ]
