# Generated by Django 4.2.16 on 2026-07-21 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0139_goimomiproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoimomiProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Holidays.goimomiproduct')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
