# Generated by Django 4.2.16 on 2026-08-03 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0142_goimomiproductorder_cart_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visaarticleimage',
            name='visa_article',
        ),
        migrations.DeleteModel(
            name='VisaArticle',
        ),
        migrations.DeleteModel(
            name='VisaArticleImage',
        ),
    ]
