# Generated by Django 4.2.16 on 2026-08-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0143_remove_visaarticleimage_visa_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goimomiproductorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50),
        ),
    ]
