# Generated by Django 4.2.16 on 2026-08-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0145_goimomiproductorder_address_line1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Logistics Provider Name (e.g. Blue Dart, Delhivery)', max_length=255)),
                ('tracking_link', models.CharField(help_text='Base tracking URL', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Logistics Provider',
                'verbose_name_plural': 'Logistics Providers',
                'ordering': ['name'],
            },
        ),
    ]
