# Generated by Django 4.2.16 on 2026-08-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0147_goimomiproductorder_book_invoice_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goimomiproductorder',
            name='bill_copy',
            field=models.FileField(blank=True, help_text='Uploaded shipping bill/receipt copy', null=True, upload_to='orders/bills/'),
        ),
    ]
