# Generated by Django 4.2.16 on 2026-08-08 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0149_visaapplication_invoice_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogueMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, help_text='Unique code or slug', max_length=100, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='catalogues/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catalogue Master',
                'verbose_name_plural': 'Catalogue Masters',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubCatalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='sub_catalogues/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display ordering position')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_catalogues', to='Holidays.cataloguemaster')),
            ],
            options={
                'verbose_name': 'Sub Catalogue',
                'verbose_name_plural': 'Sub Catalogues',
                'ordering': ['order', 'name'],
            },
        ),
    ]
