# Generated by Django 4.2.16 on 2026-08-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0151_goimomiproduct_catalogue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goimomiproduct',
            name='sub_catalogues',
            field=models.ManyToManyField(blank=True, related_name='products_multi', to='Holidays.subcatalogue'),
        ),
    ]
