# Generated by Django 4.2.16 on 2026-08-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0154_goimomiproductorder_stock_deducted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='goimomiproduct',
            name='product_id',
            field=models.CharField(blank=True, help_text='Product ID format e.g. GO-PRO-0001', max_length=100, null=True, unique=True),
        ),
    ]
