# Generated by Django 4.2.16 on 2026-08-21 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0155_goimomiproduct_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabbooking',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cabbooking',
            name='title',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
