# Generated by Django 4.2.16 on 2026-08-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0156_cabbooking_gender_alter_cabbooking_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZohoWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(default='crm_webhook', max_length=100)),
                ('module', models.CharField(blank=True, help_text='Zoho Module e.g. Leads, Contacts, Deals', max_length=100, null=True)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Raw payload received from Zoho CRM')),
                ('headers', models.JSONField(blank=True, default=dict, help_text='HTTP request headers')),
                ('status', models.CharField(choices=[('received', 'Received'), ('success', 'Success'), ('error', 'Error'), ('unauthorized', 'Unauthorized')], default='received', max_length=50)),
                ('response_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Zoho Webhook Log',
                'verbose_name_plural': 'Zoho Webhook Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
