# Generated by Django 4.2.16 on 2026-09-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0157_zohowebhooklog'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessJourneyRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=30, null=True)),
                ('journey', models.CharField(blank=True, default='Chithirai Global', max_length=150, null=True)),
                ('contacting_for', models.CharField(blank=True, default='Chithirai Global Journey Registration', max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Contacted', 'Contacted'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business Journey Registration',
                'verbose_name_plural': 'Business Journey Registrations',
                'ordering': ['-created_at'],
            },
        ),
    ]
