# Generated by Django 4.2.16 on 2026-09-22 12:57

import Holidays.profile_uploads
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0158_businessjourneyregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalHorizonsProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=255, verbose_name='Business / Profession')),
                ('photo', models.ImageField(upload_to=Holidays.profile_uploads.profile_photo_path, validators=[Holidays.profile_uploads.validate_profile_photo])),
                ('organization', models.CharField(blank=True, max_length=255, verbose_name='Organization / Brand Name')),
                ('years_of_experience', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('interests', models.TextField(max_length=5000, verbose_name='Areas of interest or expertise')),
                ('website', models.URLField(blank=True, max_length=500)),
                ('email', models.EmailField(max_length=254, verbose_name='Email address')),
                ('connections_sought', models.TextField(max_length=5000, verbose_name='Connections sought in Sri Lanka')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global Horizons - Srilanka',
                'verbose_name_plural': 'Global Horizons - Srilanka',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
