# Generated by Django 4.2.16 on 2026-09-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0159_globalhorizonsprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalhorizonsprofile',
            name='arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalhorizonsprofile',
            name='arrival_flight_no',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='globalhorizonsprofile',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalhorizonsprofile',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalhorizonsprofile',
            name='return_flight_no',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='globalhorizonsprofile',
            name='return_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalhorizonsprofile',
            name='ticket_status',
            field=models.CharField(choices=[('not_booked', 'Not Booked'), ('booked', 'Booked')], default='not_booked', max_length=20),
        ),
    ]
