# Generated by Django 4.2.16 on 2026-09-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0160_globalhorizonsprofile_arrival_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalhorizonsprofile',
            name='organization',
            field=models.CharField(max_length=255, verbose_name='Organization / Brand Name'),
        ),
    ]
