import { useState } from 'react';
import { ArrowRight, CalendarDays, Check, ChevronDown, Hotel, MapPin, Phone, ShieldCheck, Ship, Sun, Users } from 'lucide-react';
import { Link } from 'react-router-dom';
import api from '../../../api';
import usePageSEO from '../../../hooks/usePageSEO';
import TrendingDomesticDestinations from '../../../components/holidays/TrendingDomesticDestinations';
import { formatRupees, packages, rateTables } from './andamanData';
import '../TrendingDestinations/trendingDestinations.css';
import './Andaman.css';

const hero = '/images/andaman/andaman-hero.jpg';

export default function Andaman() {
  const [packageIndex, setPackageIndex] = useState(0);
  const [status, setStatus] = useState('idle');
  const [error, setError] = useState('');
  const [form, setForm] = useState({ name: '', email: '', phone: '', message: '' });
  const selected = packages[packageIndex];
  usePageSEO('Andaman Winter 2026–27 | Holiday Packages from ₹10,723 | Goimomi', 'Explore Port Blair, Ross Island, North Bay, Havelock and Radhanagar Beach with Andaman holiday packages valid October 2026 to March 2027.', '/images/andaman/andaman-hero.jpg', 'Andaman holiday package, Port Blair, Havelock Island, Radhanagar Beach, Ross Island, winter 2026');

  const updateForm = event => setForm(current => ({ ...current, [event.target.name]: event.target.value }));
  const submitEnquiry = async event => {
    event.preventDefault();
    if (!form.name.trim() || !/^[+0-9 ()-]+$/.test(form.phone) || form.phone.replace(/\D/g, '').length < 10) { setError('Please enter your name and a phone number with at least 10 digits.'); setStatus('error'); return; }
    setStatus('submitting'); setError('');
    try {
      await api.post('/api/holiday-form/', { package_type: `${selected.name} - Andaman Winter 2026–27`, start_city: 'Port Blair', nationality: 'Not specified', travel_date: '2026-10-01', rooms: 1, adults: 2, children: 0, star_rating: 'Unrated', holiday_type: 'Domestic', budget: String(selected.price), full_name: form.name.trim(), email: form.email.trim(), phone: form.phone.trim(), nights: selected.duration.split(' ')[0], cities: [{ destination: 'Port Blair', nights: selected.duration.split(' ')[0] }], room_details: [{ adults: 2, children: 0, child_ages: [] }], room_type: 'Twin sharing', meal_plan: 'Daily breakfast except arrival day', transfer_details: 'Private AC vehicle and ferry transfers as included', message: [`Source: Andaman Winter 2026–27 landing page. Package starts at ${formatRupees(selected.price)} per person.`, 'Validity: October 2026 to March 2027, except peak period 15 December 2026 to 15 January 2027.', form.message.trim()].filter(Boolean).join('\n') });
      setStatus('success');
    } catch { setStatus('error'); setError('Your enquiry could not be sent. Please try again or call +91 8110082222.'); }
  };

  return <div className="trending-page andaman-page">
    <section className="td-hero an-hero" aria-labelledby="an-title"><img className="td-hero-image" src={hero} alt="Tropical Andaman island with turquoise water, palms and a small boat" width="1600" height="900" fetchPriority="high" /><div className="td-hero-overlay" /><div className="td-container td-hero-content"><div className="td-breadcrumb"><Link to="/holidays?category=Domestic">Domestic Holidays</Link><span>/</span><span>Andaman</span></div><span className="td-eyebrow">WINTER 2026–27 · BAY OF BENGAL</span><h1 id="an-title">A little island time.<br /><em>A whole lot of Andaman.</em></h1><p>Sea breezes, colonial ruins and beaches made for slowing down.<br />Choose a Port Blair stay and let the islands unfold.</p><div className="an-hero-facts"><span><CalendarDays size={16} />October 2026 – March 2027</span><span><Users size={16} />2 adults</span><span><Ship size={16} />Ferry excursions included</span></div><div className="an-hero-actions"><a className="td-button td-button-gold" href="#an-packages">Explore packages <ArrowRight size={18} /></a><span>From <strong>{formatRupees(packages[0].price)}</strong><small>Per Person · Twin Sharing</small></span></div><div className="td-hero-caption"><MapPin size={13} />Port Blair · Sri Vijaya Puram</div></div></section>
    <div className="td-container an-snapshot">{[[Hotel, '3 or 4 nights', 'Port Blair stay'], [Sun, 'Island highlights', 'Ross, North Bay & Havelock'], [Ship, 'Ferry excursions', 'Air-conditioned vessel'], [CalendarDays, 'Winter validity', 'Oct 2026 – Mar 2027']].map(([Icon, title, detail]) => <div key={title}><Icon size={23} strokeWidth={1.5} /><span><strong>{title}</strong><small>{detail}</small></span></div>)}</div>
    <nav className="an-nav" aria-label="Andaman package sections"><div className="td-container">{[['an-itinerary', 'Itinerary'], ['an-packages', 'Packages'], ['an-inclusions', 'Inclusions'], ['an-rates', 'Rates']].map(([id, label]) => <a href={`#${id}`} key={id}>{label}</a>)}<a href="#an-enquire" className="an-nav-enquire-btn">Enquire now <ArrowRight size={14} /></a></div></nav>
    <section id="an-itinerary" className="an-soft"><div className="td-container td-section"><div className="td-section-heading"><div><span className="td-eyebrow">TWO WAYS TO TAKE THE ISLANDS IN</span><h2>Your Andaman <em>day by day.</em></h2></div><p>Both packages stay in Port Blair and include the signature island experiences below.</p></div><div className="an-itinerary-grid"><aside className="an-journey-photo"><img src={hero} alt="Tropical Andaman coastline" loading="lazy" /><div><Sun size={25} /><h3>Take the slow route.</h3><p>Salt air · clear water · island stories</p></div></aside><div className="an-days">{selected.days.map((day, index) => <details className="an-day" key={day[0]} open={index === 0}><summary><span className="an-day-number">DAY<strong>{String(index + 1).padStart(2, '0')}</strong></span><span><small>{day[2] || 'Departure'}</small><h3>{day[0]}</h3></span><ChevronDown size={18} /></summary><div className="an-day-body"><p>{day[1]}</p></div></details>)}</div></div></div></section>
    <section id="an-packages" className="td-container td-section"><div className="td-section-heading"><div><span className="td-eyebrow">CHOOSE YOUR ISLAND RHYTHM</span><h2>Two stays. <em>One beautiful escape.</em></h2></div></div><div className="an-package-grid">{packages.map((option, index) => <article className={`an-package ${packageIndex === index ? 'an-selected' : ''}`} key={option.name}><span className="td-eyebrow">OPTION {index + 1} · {option.duration}</span><h3>{option.name}</h3><p>{option.stay}</p><div className="an-price">{formatRupees(option.price)}<small>Starting Price · Per Person</small></div><ul>{option.highlights.map(item => <li key={item}><Check size={15} />{item}</li>)}</ul><button className={`td-button ${packageIndex === index ? 'td-button-green' : 'an-outline'}`} type="button" onClick={() => { setPackageIndex(index); setStatus('idle'); }} aria-pressed={packageIndex === index}>{packageIndex === index ? <><Check size={16} />Selected package</> : <>Choose this package <ArrowRight size={16} /></>}</button></article>)}</div></section>
    <section id="an-inclusions" className="an-soft"><div className="td-container td-section"><span className="td-eyebrow">THE DETAILS THAT MATTER</span><h2>Know what is <em>part of your holiday.</em></h2><div className="an-inclusion-grid">{packages.map(option => <article key={option.name}><h3>{option.name}</h3><ul>{option.inclusions.map(item => <li key={item}><Check size={15} />{item}</li>)}</ul></article>)}</div><p className="an-fine">All transfers and sightseeing are monitored by a professional tour manager. Hotel information is provided at the end of the final travel document.</p></div></section>
    <section id="an-rates" className="td-container td-section"><div className="td-section-heading"><div><span className="td-eyebrow">TRANSPARENT PACKAGE COSTS</span><h2>Pick your <em>comfort level.</em></h2></div></div>{rateTables.map(table => <div className="an-rate-table" key={table.name}><h3>{table.name}</h3><div className="an-table-scroll"><table><thead><tr><th>Category</th><th>Twin sharing</th><th>Extra adult</th><th>Child with bed</th><th>Child no bed</th></tr></thead><tbody>{table.rows.map(row => <tr key={row[0]}>{row.map((cell, index) => index === 0 ? <th scope="row" key={cell}>{cell}</th> : <td key={cell}>{formatRupees(cell)}</td>)}</tr>)}</tbody></table></div></div>)}</section>
    <section id="an-enquire" className="an-enquire"><div className="td-container an-enquire-grid"><div><span className="td-eyebrow">LET’S PLAN YOUR ISLAND ESCAPE</span><h2>Andaman,<br /><em>made easy.</em></h2><p>Share your details and our travel team will help confirm the right category, ferry schedule and hotel availability.</p><div className="an-enquiry-summary"><strong>{selected.name}</strong><span>{selected.duration} · {selected.stay}</span><p>{formatRupees(selected.price)}<small>Starting Price · Per Person</small></p></div><a href="tel:+918110082222"><Phone size={18} />+91 8110082222</a></div><div className="an-form-card">{status === 'success' ? <div className="an-success" role="status"><ShieldCheck size={44} /><h3>Your Andaman enquiry is in!</h3><p>Our travel team will contact you about availability and your final quote.</p><button className="td-button td-button-green" type="button" onClick={() => setStatus('idle')}>Make another enquiry</button></div> : <form onSubmit={submitEnquiry}><h3>Plan your Andaman holiday</h3><p>Enquiry only · no payment required</p><fieldset disabled={status === 'submitting'}><label htmlFor="an-package">Your package<select id="an-package" value={packageIndex} onChange={event => setPackageIndex(Number(event.target.value))}>{packages.map((option, index) => <option value={index} key={option.name}>{option.name} · {formatRupees(option.price)}</option>)}</select></label><div className="an-form-row"><label htmlFor="an-name">Full name<input id="an-name" name="name" value={form.name} onChange={updateForm} autoComplete="name" maxLength={100} required /></label><label htmlFor="an-phone">Phone number<input id="an-phone" name="phone" type="tel" value={form.phone} onChange={updateForm} autoComplete="tel" maxLength={20} required /></label></div><label htmlFor="an-email">Email address<input id="an-email" name="email" type="email" value={form.email} onChange={updateForm} autoComplete="email" /></label><label htmlFor="an-message">Anything else? <span>(optional)</span><textarea id="an-message" name="message" value={form.message} onChange={updateForm} rows={2} maxLength={2000} placeholder="Travel dates, room category or questions" /></label>{error && <p className="an-error" role="alert">{error}</p>}<button className="td-button td-button-green" type="submit">{status === 'submitting' ? 'Sending your enquiry…' : 'Enquire about Andaman'}<ArrowRight size={16} /></button><p className="an-privacy">By submitting, you agree to be contacted about your trip. <Link to="/privacy-policy">Privacy Policy</Link></p></fieldset></form>}</div></div></section>
    <TrendingDomesticDestinations />
  </div>;
}