# Generated by Django 4.2.16 on 2025-12-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('nights', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('enquiry_type', models.CharField(choices=[('general', 'General'), ('holiday', 'Holiday'), ('umrah', 'Umrah')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adults', models.PositiveIntegerField(default=2)),
                ('children', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HolidayEnquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(choices=[('holiday', 'Holiday'), ('umrah', 'Umrah')], max_length=20)),
                ('start_city', models.CharField(max_length=100)),
                ('travel_date', models.DateField()),
                ('nationality', models.CharField(max_length=50)),
                ('rooms', models.PositiveIntegerField()),
                ('star_rating', models.CharField(max_length=10)),
                ('holiday_type', models.CharField(blank=True, max_length=50, null=True)),
                ('budget', models.CharField(blank=True, max_length=50, null=True)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cities', models.ManyToManyField(to='Holidays.city')),
                ('room_details', models.ManyToManyField(to='Holidays.roomdetail')),
            ],
        ),
    ]
