# Generated by Django 4.2.16 on 2025-12-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UmrahCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50)),
                ('nights', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UmrahRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adults', models.PositiveIntegerField(default=2)),
                ('children', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='City',
            new_name='HolidayCity',
        ),
        migrations.RenameModel(
            old_name='RoomDetail',
            new_name='HolidayRoom',
        ),
        migrations.RenameField(
            model_name='holidaycity',
            old_name='city_name',
            new_name='destination',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='enquiry_type',
        ),
        migrations.RemoveField(
            model_name='holidayenquiry',
            name='package_type',
        ),
        migrations.AlterField(
            model_name='holidayenquiry',
            name='budget',
            field=models.CharField(blank=True, default=123, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='holidayenquiry',
            name='holiday_type',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UmrahEnquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_city', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=50)),
                ('travel_date', models.DateField()),
                ('rooms', models.PositiveIntegerField()),
                ('star_rating', models.CharField(max_length=10)),
                ('budget', models.CharField(blank=True, max_length=50)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cities', models.ManyToManyField(to='Holidays.umrahcity')),
                ('room_details', models.ManyToManyField(to='Holidays.umrahroom')),
            ],
        ),
    ]
