# Generated by Django 4.2.16 on 2025-12-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0009_holidaypackage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidaypackage',
            name='category',
            field=models.CharField(choices=[('Domestic', 'Domestic'), ('International', 'International')], default='Domestic', max_length=20),
        ),
    ]
