# Generated by Django 4.2.16 on 2025-12-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0014_holidaypackage_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidaypackage',
            name='category',
            field=models.CharField(choices=[('Domestic', 'Domestic'), ('International', 'International'), ('Umrah', 'Umrah')], default='Domestic', max_length=20),
        ),
    ]
