# Generated by Django 4.2.16 on 2025-12-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0015_alter_holidaypackage_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holidaypackage',
            name='old_price',
        ),
        migrations.AddField(
            model_name='destination',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='holidaypackage',
            name='Offer_price',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='holidaypackage',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
