# Generated by Django 4.2.16 on 2025-12-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0016_remove_holidaypackage_old_price_destination_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
