# Generated by Django 4.2.16 on 2025-12-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0019_remove_holidaypackage_destination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="A unique name to identify this template (e.g., 'Goa Arrival')", max_length=200)),
                ('title', models.CharField(help_text="The title that will appear in the package (e.g., 'Arrival and Check-in')", max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='itinerary_master/')),
            ],
        ),
    ]
