# Generated by Django 4.2.16 on 2026-01-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0021_itineraryday_master_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('continent', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Nationalities',
                'ordering': ['continent', 'country'],
            },
        ),
    ]
