# Generated by Django 4.2.16 on 2026-01-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0022_nationality'),
    ]

    operations = [
        migrations.CreateModel(
            name='UmrahDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['country', 'name'],
            },
        ),
    ]
