# Generated by Django 4.2.16 on 2026-01-06 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0024_holidayenquiry_adults_holidayenquiry_children_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='Holidays.holidaypackage')),
            ],
        ),
    ]
