# Generated by Django 4.2.16 on 2026-01-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0031_remove_visa_image_visa_card_image_visa_header_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidayenquiry',
            name='meal_plan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='holidayenquiry',
            name='nights',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='holidayenquiry',
            name='other_inclusions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='holidayenquiry',
            name='room_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='holidayenquiry',
            name='transfer_details',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
