# Generated by Django 4.2.16 on 2026-01-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0032_holidayenquiry_meal_plan_holidayenquiry_nights_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visa',
            name='method',
            field=models.CharField(choices=[('Paperless (or) E-Visa', 'Paperless (or) E-Visa'), ('Sticker Visa', 'Sticker Visa'), ('Visa Endorsement', 'Visa Endorsement')], default='Paperless (or) E-Visa', max_length=50),
        ),
        migrations.AlterField(
            model_name='visa',
            name='visa_type',
            field=models.CharField(choices=[('Paperless (or) E-Visa', 'Paperless (or) E-Visa'), ('Sticker Visa', 'Sticker Visa'), ('Visa Endorsement', 'Visa Endorsement')], default='Paperless (or) E-Visa', max_length=50),
        ),
    ]
