# Generated by Django 4.2.16 on 2026-01-19 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0034_remove_visa_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_type', models.CharField(choices=[('Individual', 'Individual'), ('Group', 'Group')], default='Individual', max_length=20)),
                ('visa_type_selected', models.CharField(max_length=100)),
                ('internal_id', models.CharField(blank=True, max_length=100, null=True)),
                ('group_name', models.CharField(blank=True, max_length=100, null=True)),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField()),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='Holidays.visa')),
            ],
        ),
        migrations.CreateModel(
            name='VisaApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('passport_number', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('dob', models.DateField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('place_of_issue', models.CharField(max_length=100)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=20)),
                ('date_of_issue', models.DateField()),
                ('date_of_expiry', models.DateField()),
                ('passport_front', models.ImageField(upload_to='visa_apps/passports/')),
                ('photo', models.ImageField(upload_to='visa_apps/photos/')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='Holidays.visaapplication')),
            ],
        ),
    ]
