# Generated by Django 4.2.16 on 2026-01-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0035_visaapplication_visaapplicant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
    ]
