# Generated by Django 4.2.16 on 2026-01-19 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0036_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.RemoveField(
            model_name='visaapplicant',
            name='application',
        ),
        migrations.RemoveField(
            model_name='visaapplication',
            name='visa',
        ),
        migrations.DeleteModel(
            name='Visa',
        ),
        migrations.DeleteModel(
            name='VisaApplicant',
        ),
        migrations.DeleteModel(
            name='VisaApplication',
        ),
    ]
