# Generated by Django 4.2.16 on 2026-01-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0040_enquiry_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='visa',
            name='visa_type',
            field=models.CharField(choices=[('Paper Visa', 'Paper Visa'), ('Sticker Visa', 'Sticker Visa')], default='Paper Visa', max_length=50),
        ),
    ]
