# Generated by Django 4.2.16 on 2026-01-21 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0042_holidaypackage_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerarymaster',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itinerary_templates', to='Holidays.destination'),
        ),
    ]
