# Generated by Django 6.0 on 2026-01-22 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0044_enquiry_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='visaapplicant',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
