# Generated by Django 4.2.16 on 2026-01-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0046_visa_photography_required_alter_visa_visa_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visa',
            name='visa_type',
            field=models.CharField(choices=[('✈️ Tourist Visa', '✈️ Tourist Visa'), ('💼 Business Visa', '💼 Business Visa'), ('🎓 Student Visa', '🎓 Student Visa'), ('👨💼 Work / Employment Visa', '👨💼 Work / Employment Visa'), ('👨👩👧 Family / Dependent Visa', '👨👩👧 Family / Dependent Visa'), ('❤️ Marriage / Fiancé(e) Visa', '❤️ Marriage / Fiancé(e) Visa'), ('🏡 Permanent Residence / Immigrant Visa', '🏡 Permanent Residence / Immigrant Visa'), ('🛂 Transit Visa', '🛂 Transit Visa'), ('🩺 Medical Visa', '🩺 Medical Visa'), ('🌍 Diplomatic / Official Visa', '🌍 Diplomatic / Official Visa')], default='✈️ Tourist Visa', max_length=100),
        ),
    ]
