# Generated by Django 4.2.16 on 2026-01-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0048_alter_visa_entry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='visa',
            name='card_image',
            field=models.ImageField(blank=True, null=True, upload_to='visas/cards/'),
        ),
        migrations.AddField(
            model_name='visa',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='visas/headers/'),
        ),
        migrations.AddField(
            model_name='visa',
            name='video',
            field=models.FileField(blank=True, help_text='Upload a video for the visa page header', null=True, upload_to='visas/videos/'),
        ),
    ]
