# Generated by Django 4.2.16 on 2026-01-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0053_visa_card_image_visa_header_image_visa_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='destination',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='enquiry_type',
            field=models.CharField(default='General', max_length=50),
        ),
    ]
