# Generated by Django 4.2.16 on 2026-01-25 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0055_remove_country_header_image_remove_country_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visa',
            name='header_image',
        ),
        migrations.RemoveField(
            model_name='visa',
            name='video',
        ),
    ]
