# Generated by Django 4.2.16 on 2026-01-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0059_visa_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visaapplicant',
            name='passport_front',
            field=models.ImageField(blank=True, null=True, upload_to='visa_apps/passports/'),
        ),
        migrations.AlterField(
            model_name='visaapplicant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='visa_apps/photos/'),
        ),
    ]
