# Generated by Django 6.0 on 2026-01-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0060_alter_visaapplicant_passport_front_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visa',
            options={'ordering': ['country', 'selling_price']},
        ),
        migrations.RemoveField(
            model_name='visa',
            name='price',
        ),
        migrations.AddField(
            model_name='visa',
            name='cost_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visa',
            name='selling_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visa',
            name='service_charge',
            field=models.IntegerField(default=0),
        ),
    ]
