# Generated by Django 4.2.16 on 2026-02-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0062_destination_card_image_destination_is_popular_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CruiseCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cruise_type', models.CharField(max_length=100)),
                ('itinerary', models.CharField(max_length=255)),
                ('jan', models.CharField(blank=True, max_length=100, null=True)),
                ('feb', models.CharField(blank=True, max_length=100, null=True)),
                ('mar', models.CharField(blank=True, max_length=100, null=True)),
                ('apr', models.CharField(blank=True, max_length=100, null=True)),
                ('may', models.CharField(blank=True, max_length=100, null=True)),
                ('jun', models.CharField(blank=True, max_length=100, null=True)),
                ('jul', models.CharField(blank=True, max_length=100, null=True)),
                ('aug', models.CharField(blank=True, max_length=100, null=True)),
                ('sep', models.CharField(blank=True, max_length=100, null=True)),
                ('oct', models.CharField(blank=True, max_length=100, null=True)),
                ('nov', models.CharField(blank=True, max_length=100, null=True)),
                ('dec', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
