# Generated by Django 4.2.16 on 2026-02-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0063_cruisecalendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='cruisecalendar',
            name='pax',
            field=models.CharField(default='Any Group Size', max_length=100),
        ),
    ]
