# Generated by Django 4.2.16 on 2026-02-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0066_hotelmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidaypackage',
            name='arrival_airport',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='holidaypackage',
            name='arrival_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='holidaypackage',
            name='arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='holidaypackage',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='holidaypackage',
            name='departure_airport',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='holidaypackage',
            name='departure_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='holidaypackage',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='holidaypackage',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='holidaypackage',
            name='with_arrival',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='holidaypackage',
            name='with_departure',
            field=models.BooleanField(default=True),
        ),
    ]
