# Generated by Django 4.2.16 on 2026-02-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0068_holidaypackage_arrival_airline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='airlines/')),
            ],
        ),
    ]
