# Generated by Django 4.2.16 on 2026-02-27 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0075_holidaypackage_ending_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sightseeingmaster',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='sightseeingmaster',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.CreateModel(
            name='SightseeingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sightseeing/gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sightseeing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Holidays.sightseeingmaster')),
            ],
        ),
    ]
