# Generated by Django 4.2.16 on 2026-02-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0077_holidaypackage_sharing'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidaypackage',
            name='fixed_departure_data',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
