# Generated by Django 4.2.16 on 2026-03-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0081_roomtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidaypackage',
            name='sharing',
            field=models.CharField(blank=True, choices=[('SINGLE', 'SINGLE'), ('TWIN', 'TWIN'), ('TRIPLE', 'TRIPLE'), ('QUAD', 'QUAD'), ('QUINT', 'QUINT')], default='SINGLE', max_length=20, null=True),
        ),
    ]
