# Generated by Django 4.2.16 on 2026-03-05 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0084_drivermaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemaster',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='Holidays.drivermaster'),
        ),
    ]
