# Generated by Django 4.2.16 on 2026-03-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0085_vehiclemaster_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleRateCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('validity_start', models.DateField()),
                ('validity_end', models.DateField()),
                ('routes', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
