# Generated by Django 4.2.16 on 2026-03-05 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0086_vehicleratecard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemaster',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='Holidays.vehiclebrand'),
        ),
        migrations.AlterField(
            model_name='vehiclemaster',
            name='drive',
            field=models.CharField(blank=True, choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], default='Manual', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemaster',
            name='luggage_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemaster',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemaster',
            name='seating_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
