# Generated by Django 4.2.16 on 2026-03-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0089_accommodation_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=255)),
                ('vehicle_category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('from_city', models.CharField(max_length=255)),
                ('to_city', models.CharField(max_length=255)),
                ('pickup_date', models.DateField()),
                ('guests', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=25)),
                ('luggage_count', models.CharField(blank=True, max_length=50, null=True)),
                ('transfer_type', models.CharField(max_length=50)),
                ('flight_number', models.CharField(blank=True, max_length=50, null=True)),
                ('terminal', models.CharField(blank=True, max_length=50, null=True)),
                ('arrival_time', models.CharField(blank=True, max_length=50, null=True)),
                ('departure_time', models.CharField(blank=True, max_length=50, null=True)),
                ('pickup_location_details', models.TextField(blank=True, null=True)),
                ('pickup_time', models.CharField(blank=True, max_length=50, null=True)),
                ('special_requirements', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
