# Generated by Django 4.2.16 on 2026-03-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0091_remove_vehiclemaster_drive'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleratecard',
            name='column_vehicles',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
