# Generated by Django 4.2.16 on 2026-03-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0093_cabbooking_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabbooking',
            name='driver',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cabbooking',
            name='status',
            field=models.CharField(choices=[('Booking requested', 'Booking requested'), ('Payment Pending', 'Payment Pending'), ('Confirmed', 'Confirmed'), ('Canceled', 'Canceled')], default='Booking requested', max_length=50),
        ),
    ]
