# Generated by Django 4.2.16 on 2026-03-09 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0094_cabbooking_driver_cabbooking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleratecard',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rate_cards', to='Holidays.supplier'),
        ),
    ]
