# Generated by Django 4.2.16 on 2026-03-10 11:11

from django.db import migrations


def seed_master_data(apps, schema_editor):
    VehicleBrand = apps.get_model('Holidays', 'VehicleBrand')
    RoomType = apps.get_model('Holidays', 'RoomType')

    brands = [
        "Maruti Suzuki", "Tata Motors", "Mahindra", "Ashok Leyland", "Force Motors",
        "Hindustan Motors", "Premier", "ICML", "Toyota", "Lexus", "Honda", "Acura",
        "Nissan", "Infiniti", "Mazda", "Subaru", "Mitsubishi", "Suzuki", "Daihatsu",
        "Isuzu", "Mercedes-Benz", "BMW", "Audi", "Volkswagen", "Porsche", "Opel",
        "Maybach", "Smart", "Ford", "Chevrolet", "GMC", "Cadillac", "Buick",
        "Chrysler", "Dodge", "Jeep", "Tesla", "Lincoln", "Rivian", "Lucid",
        "Rolls-Royce", "Bentley", "Jaguar", "Land Rover", "Mini", "Aston Martin",
        "McLaren", "Lotus", "MG", "Renault", "Peugeot", "Citroën", "DS Automobiles",
        "Bugatti", "Ferrari", "Lamborghini", "Maserati", "Alfa Romeo", "Fiat",
        "Pagani", "Lancia", "Hyundai", "Kia", "Genesis", "Daewoo", "SsangYong",
        "BYD", "Geely", "Chery", "Great Wall", "Haval", "Wuling", "SAIC", "NIO",
        "XPeng", "Li Auto", "Hongqi", "Volvo", "Polestar", "Koenigsegg", "SEAT",
        "Cupra", "Skoda", "Lada", "GAZ", "UAZ", "Fisker", "VinFast", "Ora",
        "Ather", "Ola Electric"
    ]

    for brand_name in sorted(list(set(brands))):
        VehicleBrand.objects.get_or_create(name=brand_name)

    room_types = [
        "Single Room", "Double Room", "Twin Room", "Triple Room", "Quad Room",
        "Standard Room", "Superior Room", "Deluxe Room", "Executive Room",
        "King Room", "Queen Room", "Double Queen Room", "Twin Bed Room",
        "Hollywood Twin Room", "Murphy Bed Room", "Suite", "Junior Suite",
        "Executive Suite", "Presidential Suite", "Royal Suite", "Family Suite",
        "Honeymoon Suite", "Penthouse Suite", "Studio Room", "Loft Room",
        "Cabana Room", "Villa", "Beachfront Room", "Overwater Bungalow",
        "Cottage", "Chalet", "Bungalow", "Tree House", "Family Room",
        "Interconnecting Room", "Adjoining Room", "Dormitory Room", "Shared Room",
        "Accessible Room", "Disabled Friendly Room", "Hearing Accessible Room",
        "Wheelchair Accessible Room", "Business Room", "Club Room",
        "Executive Floor Room", "High Floor Room", "Corner Room", "Sea View Room",
        "Ocean View Room", "City View Room", "Garden View Room", "Mountain View Room",
        "Pool View Room", "Lake View Room", "Serviced Apartment", "Residence Room",
        "Extended Stay Room", "Kitchenette Room", "Economy Room", "Budget Room",
        "Compact Room", "Micro Room", "Capsule Room"
    ]

    for rt_name in room_types:
        RoomType.objects.get_or_create(name=rt_name)

class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0097_cabbooking_confirmation_doc_cabadditionaldocument'),
    ]

    operations = [
        migrations.RunPython(seed_master_data),
    ]
