# Generated by Django 4.2.16 on 2026-03-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0098_seed_master_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabbooking',
            name='status',
            field=models.CharField(choices=[('Booking requested', 'Booking requested'), ('Tentative Confirmation', 'Tentative Confirmation'), ('Cancelled', 'Cancelled')], default='Booking requested', max_length=50),
        ),
    ]
