# Generated by Django 4.2.16 on 2026-03-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0099_alter_cabbooking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabbooking',
            name='status',
            field=models.CharField(choices=[('Booking requested', 'Booking requested'), ('Tentative Confirmation', 'Tentative Confirmation'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Booking requested', max_length=50),
        ),
    ]
