# Generated by Django 4.2.16 on 2026-03-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0105_alter_cabbooking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabbooking',
            name='status',
            field=models.CharField(choices=[('Booking Requested', 'Booking Requested'), ('Tentative Confirmation', 'Tentative Confirmation'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Booking Requested', max_length=50),
        ),
    ]
