# Generated by Django 4.2.16 on 2026-03-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0106_alter_cabbooking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleratecard',
            name='rate_card_file',
            field=models.FileField(blank=True, null=True, upload_to='rate_cards/'),
        ),
    ]
