# Generated by Django 4.2.16 on 2026-03-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0108_holidaypackage_accommodations_raw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidaypackage',
            name='cancellation_policies_raw',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='holidaypackage',
            name='exclusions_raw',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='holidaypackage',
            name='highlights_raw',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='holidaypackage',
            name='inclusions_raw',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='holidaypackage',
            name='vehicles_raw',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
