# Generated by Django 4.2.16 on 2026-03-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0109_holidaypackage_cancellation_policies_raw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidaypackage',
            name='terms_and_policies_raw',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
