# Generated by Django 4.2.16 on 2026-03-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0111_cantonenquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidaypackage',
            name='category',
            field=models.CharField(choices=[('Domestic', 'Domestic'), ('International', 'International'), ('Umrah', 'Umrah'), ('Business Trip', 'Business Trip')], default='Domestic', max_length=20),
        ),
    ]
