# Generated by Django 4.2.16 on 2026-03-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0112_alter_holidaypackage_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='enquiry_type',
            field=models.CharField(choices=[('General', 'General'), ('Cab', 'Cab'), ('Cruise', 'Cruise'), ('Business Trip', 'Business Trip')], default='General', max_length=50),
        ),
    ]
