# Generated by Django 4.2.16 on 2026-03-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0113_alter_enquiry_enquiry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='enquiry_type',
            field=models.CharField(choices=[('General', 'General'), ('Cab', 'Cab'), ('Cruise', 'Cruise'), ('Business Travel', 'Business Travel')], default='General', max_length=50),
        ),
        migrations.AlterField(
            model_name='holidaypackage',
            name='category',
            field=models.CharField(choices=[('Domestic', 'Domestic'), ('International', 'International'), ('Umrah', 'Umrah'), ('Business Travel', 'Business Travel')], default='Domestic', max_length=20),
        ),
    ]
