# Generated by Django 4.2.16 on 2026-04-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0114_alter_enquiry_enquiry_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabbooking',
            name='status',
            field=models.CharField(choices=[('Booking Requested', 'Booking Requested'), ('Tentative Confirmation', 'Tentative Confirmation'), ('defined', 'defined'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Booking Requested', max_length=50),
        ),
    ]
