# Generated by Django 4.2.16 on 2026-04-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0115_alter_cabbooking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='from_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='to_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='travel_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='vehicle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
