# Generated by Django 4.2.16 on 2026-04-04 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0116_enquiry_from_city_enquiry_to_city_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='StartingCity',
        ),
        migrations.DeleteModel(
            name='UmrahDestination',
        ),
    ]
