# Generated by Django 4.2.16 on 2026-04-04 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0118_alter_cabbooking_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nationality',
        ),
    ]
