# Generated by Django 4.2.16 on 2026-04-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0119_delete_nationality'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='visaapplicant',
            name='nationality',
        ),
    ]
