# Generated by Django 4.2.16 on 2026-04-04 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0124_airport'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='airports', to='Holidays.city'),
        ),
    ]
