# Generated by Django 4.2.16 on 2026-04-04 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0127_alter_region_name_alter_region_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'region', 'country')},
        ),
    ]
