# Generated by Django 4.2.16 on 2026-04-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0129_nationality_country_alter_city_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabbooking',
            name='airport_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
