# Generated by Django 4.2.16 on 2026-05-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0132_remove_accommodation_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='card_image',
            field=models.ImageField(blank=True, null=True, upload_to='countries/cards/'),
        ),
    ]
