# Generated by Django 4.2.16 on 2026-07-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0134_cabbooking_booking_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='cabbooking',
            name='status',
            field=models.CharField(choices=[('Booking Requested', 'Booking Requested'), ('Tentative Confirmation', 'Tentative Confirmation'), ('defined', 'defined'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Booking Requested', max_length=50),
        ),
    ]
