# Generated by Django 4.2.16 on 2026-07-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0136_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabbooking',
            name='zoho_access_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cabbooking',
            name='zoho_payment_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
