# Generated by Django 4.2.16 on 2026-07-21 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0140_goimomiproductimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoimomiProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, help_text='Unit price at checkout', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount paid', max_digits=10)),
                ('address', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50)),
                ('zoho_payment_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('zoho_access_key', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='Holidays.goimomiproduct')),
            ],
            options={
                'verbose_name': 'Goimomi Product Order',
                'verbose_name_plural': 'Goimomi Product Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
