# Generated by Django 4.2.16 on 2026-07-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0141_goimomiproductorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='goimomiproductorder',
            name='cart_items',
            field=models.JSONField(blank=True, help_text='Cart items list if cart checkout', null=True),
        ),
    ]
