# Generated by Django 4.2.16 on 2026-08-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0146_logisticsprovider'),
    ]

    operations = [
        migrations.AddField(
            model_name='goimomiproductorder',
            name='book_invoice_number',
            field=models.CharField(blank=True, help_text='Custom / Offline Book Invoice Number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goimomiproductorder',
            name='logistics_provider',
            field=models.CharField(blank=True, help_text='Courier / Logistics Provider Name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goimomiproductorder',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='Courier Tracking / Waybill Number', max_length=100, null=True),
        ),
    ]
