# Generated by Django 4.2.16 on 2026-08-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0152_goimomiproduct_sub_catalogues'),
    ]

    operations = [
        migrations.AddField(
            model_name='goimomiproductorder',
            name='pincode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
