# Generated by Django 4.2.16 on 2026-08-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0153_goimomiproductorder_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='goimomiproductorder',
            name='stock_deducted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
