# Generated by Django 5.1.2 on 2025-12-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goimomiapp', '0003_customizedholiday_customizedumrah'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('passport_expiry_date', models.DateField(blank=True, null=True)),
                ('destination_country', models.CharField(max_length=100)),
                ('visa_type', models.CharField(max_length=50)),
                ('intended_travel_date', models.DateField(blank=True, null=True)),
                ('processing_urgency', models.CharField(blank=True, max_length=20, null=True)),
                ('purpose_of_visit', models.TextField(blank=True, null=True)),
                ('previous_visa_rejection', models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], max_length=3, null=True)),
                ('special_requirements', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
