import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, CalendarDays, CarFront, Check, ChevronDown, Hotel, MapPin, Mountain, Phone, ShieldCheck, Users, Utensils, X } from 'lucide-react';
import api from '../../../api';
import TrendingDomesticDestinations from '../../../components/holidays/TrendingDomesticDestinations';
import usePageSEO from '../../../hooks/usePageSEO';
import { days, exclusions, inclusions, information, rupees, stays, travelDate } from './manaliData';
import '../TrendingDestinations/trendingDestinations.css';
import './Manali.css';

export default function Manali() {
  const [stayIndex, setStayIndex] = useState(0);
  const [form, setForm] = useState({ name: '', email: '', phone: '', message: '' });
  const [status, setStatus] = useState('idle');
  const [error, setError] = useState('');
  const stay = stays[stayIndex];
  usePageSEO('Chandigarh – Manali | 3 Nights / 4 Days | Goimomi Holidays', 'Explore Manali, Solang Valley, Atal Tunnel and Kullu. 26–29 November 2026, private sedan, 3 breakfasts and 3 dinners. From ₹11,750 per adult on a twin-sharing basis.', '/images/manali/manali-social.jpg', 'Manali holiday package, Chandigarh Manali, Solang Valley, Atal Tunnel, Kullu, November 2026');
  usePageSEO('Chandigarh – Manali | 3 Nights / 4 Days | Goimomi Holidays', 'Explore Manali, Solang Valley, Atal Tunnel and Kullu. Private sedan, 3 breakfasts and 3 dinners. From ₹11,750 per adult on a twin-sharing basis.', '/images/manali/manali-social.jpg', 'Manali holiday package, Chandigarh Manali, Solang Valley, Atal Tunnel, Kullu');

  const chooseStay = index => { if (status !== 'submitting') { setStayIndex(index); setStatus('idle'); setError(''); } };
  const updateForm = event => setForm(current => ({ ...current, [event.target.name]: event.target.value }));
  const submitEnquiry = async event => {
    event.preventDefault();
    if (status === 'submitting') return;
    if (!form.name.trim() || !/^[+0-9 ()-]+$/.test(form.phone) || form.phone.replace(/\D/g, '').length < 10) { setError('Please enter your name and a phone number with at least 10 digits.'); setStatus('error'); return; }
    setStatus('submitting'); setError('');
    try {
      await api.post('/api/holiday-form/', {
        package_type: `Chandigarh Manali - ${stay.name} - 3N / 4D`, start_city: 'Chandigarh', nationality: 'Not specified', travel_date: travelDate,
        rooms: 1, adults: 2, children: 0, star_rating: 'Unrated', holiday_type: 'Domestic', budget: String(stay.price),
        full_name: form.name.trim(), email: form.email.trim(), phone: form.phone.trim(), nights: 3,
        cities: [{ destination: 'Manali', nights: 3 }], room_details: [{ adults: 2, children: 0, child_ages: [] }], room_type: stay.room,
        meal_plan: '3 breakfasts and 3 dinners', transfer_details: 'Private sedan for 4 days; Chandigarh pickup and drop',
        message: ['Source: Manali landing page. Enquiry only; subject to availability and booking confirmation.', `${stay.name}: ${stay.hotels.join(' / ')} or similar-category property; 1 ${stay.room}.`, `Price per adult on twin sharing: INR ${stay.price / 2}. Price for 2 adults together: INR ${stay.price}.`, 'Solang Valley and Atal Tunnel subject to accessibility. Adventure activities and union vehicles extra.', form.message].filter(Boolean).join('\n'),
      });
      setStatus('success');
    } catch { setStatus('error'); setError('Your enquiry could not be sent. Please try again or call +91 8110082222.'); }
  };

  return <div className="trending-page manali-page">
    <section className="td-hero ml-hero" aria-labelledby="ml-title"><img className="td-hero-image" src="/images/manali/manali-hero.webp" alt="Manali-inspired Himalayan valley with pine forests, snow-capped peaks and the Beas River" fetchPriority="high" width="1672" height="941" /><div className="td-hero-overlay" /><div className="td-container td-hero-content"><div className="td-breadcrumb"><Link to="/trendingdomesticdestination">Trending Domestic Destination</Link><span>/</span><span>Manali</span></div><span className="td-eyebrow">YOUR HIMALAYAN ESCAPE STARTS IN CHANDIGARH.</span><h1 id="ml-title">A little mountain magic.<br /><em>A whole lot of Manali.</em></h1><p>Scenic drives, peaceful temples and spectacular valleys.<br />Four days to breathe deeper and explore Himachal Pradesh together.</p><div className="ml-hero-facts"><span><CalendarDays size={16} />3 nights / 4 days</span><span><Users size={16} />2 adults</span><span><CarFront size={16} />Private sedan</span></div><div className="ml-hero-actions"><a className="td-button td-button-gold" href="#ml-stays">Find your mountain stay <ArrowRight size={18} /></a><span>From <strong>{rupees(stays[0].price / 2)}</strong><small>per adult · twin sharing</small></span></div><div className="td-hero-caption"><MapPin size={13} />Inspired by Manali</div></div></section>
    <div className="ml-snapshot td-container">{[[Hotel, '3 nights in Manali', '1 room for 2 adults'], [Utensils, 'Meals included', '3 breakfasts + 3 dinners'], [CarFront, 'Private sedan', '4 days, as per itinerary'], [MapPin, 'Chandigarh return', 'Pickup & drop included']].map(([Icon, title, detail]) => <div key={title}><Icon size={23} strokeWidth={1.5} /><span><strong>{title}</strong><small>{detail}</small></span></div>)}</div>
    <nav className="ml-nav" aria-label="Manali package sections"><div className="td-container">{[['ml-journey', 'Your journey'], ['ml-itinerary', 'Itinerary'], ['ml-stays', 'Stays & prices'], ['ml-inclusions', 'Inclusions'], ['ml-info', 'Good to know']].map(([id, label]) => <a key={id} href={`#${id}`}>{label}</a>)}<a href="#ml-enquire" className="ml-nav-enquire-btn">Enquire now <ArrowRight size={14} /></a></div></nav>
    <section id="ml-journey" className="td-container td-section ml-intro"><div><span className="td-eyebrow">3 NIGHTS / 4 DAYS · HIMACHAL PRADESH</span><h2>The mountains are calling.<br /><em>Make the journey yours.</em></h2></div><div><p>Escape to Manali with comfortable accommodation, a private cab and your breakfasts and dinners taken care of. Explore its cultural sights, the dramatic landscapes of Solang Valley and Atal Tunnel, and Kullu on your way back.</p><div className="ml-route">Chandigarh <ArrowRight size={13} /> Manali <ArrowRight size={13} /> Solang Valley <ArrowRight size={13} /> Atal Tunnel <ArrowRight size={13} /> Kullu <ArrowRight size={13} /> Chandigarh</div><p className="ml-fine">Package rate validity: 11 July–20 December 2026.</p></div></section>
    <section id="ml-itinerary" className="ml-soft"><div className="td-container td-section"><div className="td-section-heading"><div><span className="td-eyebrow">FOUR DAYS. A FRESH PERSPECTIVE.</span><h2>Your day-by-day <em>mountain escape.</em></h2></div><p>Three nights in Manali, with Chandigarh pickup and drop.</p></div><div className="ml-itinerary-grid"><div className="ml-photo"><img src="/images/manali/manali-hero.webp" alt="Manali-inspired mountain scenery" loading="lazy" /><div><Mountain size={26} /><h3>Take the scenic route.</h3><p>A little closer to nature.<br />A little further from the everyday.</p></div></div><div>{days.map((day, index) => <details className="ml-day" key={day.title} open={index === 0 ? true : undefined}><summary><span className="ml-day-number">DAY<strong>{String(index + 1).padStart(2, '0')}</strong></span><span><h3>{day.title}</h3></span><ChevronDown size={18} /></summary><div className="ml-day-body"><p>{day.description}</p>{day.distance && <p className="ml-distance"><CarFront size={15} />{day.distance}</p>}<ul className="ml-tags">{day.places.map(place => <li key={place}>{place}</li>)}</ul>{day.note && <p className="ml-day-note">{day.note}</p>}<div className="ml-day-footer"><span><Utensils size={14} />{day.meals}</span>{day.overnight && <span><Hotel size={14} />Overnight: {day.overnight}</span>}</div></div></details>)}</div></div></div></section>
    <section id="ml-stays" className="td-container td-section"><div className="td-section-heading"><div><span className="td-eyebrow">YOUR STAY. YOUR LEVEL OF COMFORT.</span><h2>Three ways to <em>feel at home.</em></h2></div><p>Every option includes the same private itinerary and meals. Prices are per adult on a twin-sharing basis (2 adults sharing 1 room).</p></div><div className="ml-stay-grid">{stays.map((option, index) => <article key={option.name} className={`ml-stay ${stayIndex === index ? 'ml-selected' : ''}`}><span className="td-eyebrow">OPTION {index + 1} · {option.room.toUpperCase()}</span><h3>{option.name}</h3><div className="ml-price">{rupees(option.price / 2)}<small>per adult · twin sharing</small></div><ul className="ml-hotels">{option.hotels.map(hotel => <li key={hotel}><Hotel size={14} />{hotel}</li>)}<li>Or a similar-category hotel</li></ul><button className={`td-button ${stayIndex === index ? 'td-button-green' : 'ml-outline'}`} type="button" aria-pressed={stayIndex === index} onClick={() => chooseStay(index)} disabled={status === 'submitting'}>{stayIndex === index ? <><Check size={16} />Selected stay</> : <>Choose this stay <ArrowRight size={16} /></>}</button></article>)}</div><div className="ml-selection" aria-live="polite"><span><strong>{stay.name}</strong> · {stay.room} · {rupees(stay.price / 2)} per adult · twin sharing</span><a href="#ml-enquire">Enquire for this package <ArrowRight size={15} /></a></div><p className="ml-fine">Hotel accommodation is subject to availability. A similar-category property may be provided. Rates valid 11 July–20 December 2026; other dates or arrangements require confirmation.</p></section>
    <section id="ml-inclusions" className="ml-soft"><div className="td-container td-section"><span className="td-eyebrow">ALL THE DETAILS, CLEARLY LAID OUT.</span><h2>Know what’s <em>part of your holiday.</em></h2><div className="ml-inclusion-grid"><article><h3>Package inclusions</h3><ul>{inclusions.map(item => <li key={item}><Check size={15} /><span>{item}</span></li>)}</ul></article><article><h3>Package exclusions</h3><ul>{exclusions.map(item => <li key={item}><X size={15} /><span>{item}</span></li>)}</ul></article></div></div></section>
    <section id="ml-info" className="td-container td-section"><div className="td-section-heading"><div><span className="td-eyebrow">A LITTLE PLANNING GOES A LONG WAY.</span><h2>Before you <em>head for the hills.</em></h2></div></div><div className="ml-information">{information.map((item, index) => <div key={item}><span>{String(index + 1).padStart(2, '0')}</span><p>{item}</p></div>)}</div></section>
    <section id="ml-enquire" className="ml-enquire"><div className="td-container ml-enquire-grid"><div className="ml-enquire-copy"><span className="td-eyebrow">LET’S MAKE YOUR MOUNTAIN ESCAPE HAPPEN.</span><h2>A Manali holiday,<br /><em>made for you.</em></h2><p>Share your details and we’ll help confirm your preferred stay and Chandigarh-to-Chandigarh holiday.</p><div className="ml-enquiry-summary"><strong>{stay.name} · {stay.room}</strong><span>3 nights / 4 days · 2 adults · 1 room</span><p>{rupees(stay.price / 2)}<small>per adult · twin sharing</small></p><span>Package total for 2 adults: {rupees(stay.price)}</span></div><a href="tel:+918110082222"><Phone size={18} />+91 8110082222</a></div><div className="ml-form-card">{status === 'success' ? <div className="ml-success" role="status"><ShieldCheck size={45} /><h3>Your Manali enquiry is in!</h3><p>Our travel team will contact you about availability and your final quote. Your booking is confirmed only after the arrangements are agreed.</p><button className="td-button td-button-green" type="button" onClick={() => setStatus('idle')}>Make another enquiry</button></div> : <form onSubmit={submitEnquiry}><h3>Plan your Manali holiday</h3><p>Enquiry only · no payment required</p><fieldset disabled={status === 'submitting'}><label htmlFor="ml-stay">Your stay<select id="ml-stay" value={stayIndex} onChange={event => chooseStay(Number(event.target.value))}>{stays.map((option, index) => <option value={index} key={option.name}>{option.name} · {rupees(option.price / 2)} per adult · twin sharing</option>)}</select></label><div className="ml-form-row"><label htmlFor="ml-name">Full name<input id="ml-name" name="name" autoComplete="name" value={form.name} onChange={updateForm} maxLength={100} required /></label><label htmlFor="ml-phone">Phone number<input id="ml-phone" name="phone" type="tel" autoComplete="tel" value={form.phone} onChange={updateForm} maxLength={20} required /></label></div><label htmlFor="ml-email">Email address<input id="ml-email" name="email" type="email" autoComplete="email" value={form.email} onChange={updateForm} maxLength={254} required /></label><label htmlFor="ml-dates">Package duration<input id="ml-dates" value="3 nights / 4 days" readOnly /></label><label htmlFor="ml-message">Anything else? <span>(optional)</span><textarea id="ml-message" name="message" rows={2} value={form.message} onChange={updateForm} maxLength={2000} placeholder="Pickup details, preferences or a request for different dates…" /></label>{error && <p className="ml-error" role="alert">{error}</p>}<button className="td-button td-button-green" type="submit">{status === 'submitting' ? 'Sending your enquiry…' : 'Enquire about Manali'}<ArrowRight size={16} /></button><p className="ml-privacy">By submitting, you agree to be contacted about your trip. <Link to="/privacy-policy">Privacy Policy</Link></p></fieldset></form>}</div></div></section>
    <TrendingDomesticDestinations />
    <div className="ml-back"><Link to="/trendingdomesticdestination">Explore more domestic destinations <ArrowRight size={16} /></Link></div>
  </div>;
}
