"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(os.path.join(BASE_DIR, '.env'), override=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-&t4_sd6+&#m!@p4e$n7@+84rtr$+p@qcv8*&et75u9ck1q!2tk')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

_cors_origins = os.getenv(
    'CORS_ALLOWED_ORIGINS',
    'https://goimomi.com,https://www.goimomi.com,http://localhost:5174,http://127.0.0.1:5174',
)
CORS_ALLOWED_ORIGINS = [origin.strip().rstrip('/') for origin in _cors_origins.split(',') if origin.strip()]
CORS_ALLOW_ALL_ORIGINS = DEBUG

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'goimomi.com,www.goimomi.com,54.81.116.105,localhost,127.0.0.1').split(',')

# Secure Proxy SSL Header
# This tells Django it's behind a proxy that handles SSL
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_spectacular',
    'Holidays', 
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'goimomi_db'),
        'USER': os.getenv('DB_USER', 'goimomi_user'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'Goimomi@123'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
        'CONN_MAX_AGE': 600,
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'static'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '30/minute',
        'user': '120/minute'
    }
}

if DEBUG:
    REST_FRAMEWORK['DEFAULT_RENDERER_CLASSES'].append('rest_framework.renderers.BrowsableAPIRenderer')

SPECTACULAR_SETTINGS = {
    'TITLE': 'Goimomi Holidays API',
    'DESCRIPTION': 'Complete RESTful API for Goimomi Holidays platform',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

from decouple import config

# Email Settings
EMAIL_BACKEND = config("EMAIL_BACKEND")
EMAIL_HOST = config("EMAIL_HOST")
EMAIL_PORT = config("EMAIL_PORT", cast=int)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", cast=bool)
EMAIL_HOST_USER = config("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL")
COMPANY_EMAIL = config("COMPANY_EMAIL")

# Zoho CRM Configuration
ZOHO_CRM_REFRESH_TOKEN = config("ZOHO_CRM_REFRESH_TOKEN", default="")
ZOHO_CRM_CLIENT_ID = config("ZOHO_CRM_CLIENT_ID", default="")
ZOHO_CRM_CLIENT_SECRET = config("ZOHO_CRM_CLIENT_SECRET", default="")
ZOHO_CRM_WEBHOOK_SECRET = config("ZOHO_CRM_WEBHOOK_SECRET", default="goimomi-zoho-webhook-secret-2026")
FRONTEND_URL = config("FRONTEND_URL", default="https://goimomi.com")

# Twilio Configuration
TWILIO_ACCOUNT_SID = config("TWILIO_ACCOUNT_SID", default="")
TWILIO_AUTH_TOKEN = config("TWILIO_AUTH_TOKEN", default="")
TWILIO_WHATSAPP_NUMBER = config("TWILIO_WHATSAPP_NUMBER", default="")

# Zoho Payments Configuration
ZOHO_PAYMENTS_ACCOUNT_ID = config("ZOHO_PAYMENTS_ACCOUNT_ID", default="")
ZOHO_PAYMENTS_EDITION = config("ZOHO_PAYMENTS_EDITION", default="IN_SANDBOX")
ZOHO_PAYMENTS_CLIENT_ID = config("ZOHO_PAYMENTS_CLIENT_ID", default="")
ZOHO_PAYMENTS_CLIENT_SECRET = config("ZOHO_PAYMENTS_CLIENT_SECRET", default="")
ZOHO_PAYMENTS_REFRESH_TOKEN = config("ZOHO_PAYMENTS_REFRESH_TOKEN", default="")
ZOHO_PAYMENTS_REDIRECT_URI = config("ZOHO_PAYMENTS_REDIRECT_URI", default="https://goimomi.com")
ZOHO_PAYMENTS_WEBHOOK_ID = config("ZOHO_PAYMENTS_WEBHOOK_ID", default="")
ZOHO_PAYMENTS_WEBHOOK_SIGNING_KEY = config("ZOHO_PAYMENTS_WEBHOOK_SIGNING_KEY", default="")
ZOHO_PAYMENTS_SIGNING_KEY = config("ZOHO_PAYMENTS_SIGNING_KEY", default="")

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
}

# Production Security Hardening
if not DEBUG:
    # SECURE_SSL_REDIRECT is enabled for production security
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000 # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# Suppress noisy "HTTPS-over-HTTP" probe warnings in the dev server terminal.
# These come from browser extensions, antivirus tools, or Chrome HSTS probing
# port 8000 with HTTPS. They are harmless but very noisy.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'suppress_https_noise': {
            '()': 'django.utils.log.CallbackFilter',
            'callback': lambda record: not (
                'Bad request version' in str(record.getMessage()) or
                'Bad HTTP/0.9 request type' in str(record.getMessage()) or
                "You're accessing the development server over HTTPS" in str(record.getMessage())
            ),
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'filters': ['suppress_https_noise'],
        },
    },
    'loggers': {
        'django.server': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# ── Celery & Redis Configuration ──────────────────────────────────────────────
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://127.0.0.1:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60

# Celery Beat Scheduled Tasks
CELERY_BEAT_SCHEDULE = {
    'sync-pending-orders-every-5-mins': {
        'task': 'Holidays.tasks.cleanup_or_sync_pending_orders_task',
        'schedule': 300.0,
    },
}
